/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIO.VISTA;

//import java.awt.event.ActionEvent;
//import java.awt.event.ActionListener;
//import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Digno
 */
public class FrmProgreso extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmProgreso
     */
//    Timer t;
    int maximo_progreso = 100;

    void abrir_formulario() {
        jProgreso_teste.setMaximum(maximo_progreso);
        jProgreso_teste.setValue(0);
        jProgreso_teste.setStringPainted(true);
    }

    class Avanzando implements Runnable {

        JProgressBar bar;
        int num_bar = 1;

        @Override
        public void run() {
            for (int porcentaje = 0; porcentaje <= maximo_progreso; porcentaje++) {
                try {
                    Thread.sleep(100);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Avanzando.class.getName()).log(Level.SEVERE, null, ex);
                }

                this.getBar().setValue(porcentaje);

                if (this.getBar().getValue() == maximo_progreso) {
                    JOptionPane.showMessageDialog(new FrmProgreso(), "Ha terminado el Jbar No: " + num_bar);
                }
            }
            num_bar++;
        }

        public void setBar(JProgressBar bar) {
            this.bar = bar;
        }

        public JProgressBar getBar() {
            return bar;
        }
    }

    public FrmProgreso() {
        initComponents();
        abrir_formulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgreso_teste = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("PROGRESO");

        jButton1.setText("INICIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jProgreso_teste, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jProgreso_teste, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Avanzando avanzando = new Avanzando();
        avanzando.setBar(jProgreso_teste);
        Thread hilo = new Thread(avanzando);
        hilo.start();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JProgressBar jProgreso_teste;
    // End of variables declaration//GEN-END:variables
}
