/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIO.VISTA;

import BASEDATO.EvenConexion;
import BASEDATO.LOCAL.ConnPostgres;
import Evento.Color.cla_color_palete;
import Evento.Combobox.EvenCombobox;
import Evento.Fecha.EvenFecha;
import Evento.JLabel.EvenJLabel;
import Evento.Jframe.EvenJFRAME;
import Evento.Jtable.EvenJtable;
import Evento.Mensaje.EvenMensajeJoptionpane;
import FORMULARIO.DAO.DAO_caja_detalle;
import java.sql.Connection;
import java.sql.ResultSet;

/**
 *
 * @author Digno
 */
public class FrmRepMovimientoCaja extends javax.swing.JInternalFrame {

    EvenJFRAME evetbl = new EvenJFRAME();
    EvenJtable eveJtab = new EvenJtable();
    EvenCombobox evecomb = new EvenCombobox();
    EvenJLabel evelbl = new EvenJLabel();
    EvenFecha evefec = new EvenFecha();
    EvenConexion eveconn = new EvenConexion();
    EvenMensajeJoptionpane evemen = new EvenMensajeJoptionpane();
    Connection conn = ConnPostgres.getConnPosgres();
    cla_color_palete clacolor = new cla_color_palete();
    private DAO_caja_detalle DAOcd = new DAO_caja_detalle();

    private void abrir_formulario() {
        this.setTitle("DATOS CAJA");
        evetbl.centrar_formulario_internalframa(this);
//        actualizar_tabla_todos();
        actualizar_tabla_suma();
        evefec.cargar_combobox_intervalo_fecha(cmbfecha_caja);
    }

//    void actualizar_tabla_todos() {
//        DAOcd.actualizar_caja_detalle_todos(conn, tbltablatodos);
//    }

    void actualizar_tabla_suma() {
        String fecha = evefec.getIntervalo_fecha_combobox(cmbfecha_caja, " cd.fecha_creado ");
        DAOcd.actualizar_caja_detalle_suma(conn, tblcaja_suma, fecha);
        DAOcd.actualizar_caja_detalle_todos(conn, tbltablatodos,fecha);
        cargar_sumas_caja(fecha);
    }

    public void cargar_sumas_caja(String fecha) {
        String titulo = "cargar_pre_item_liquidacion";
        String sql = "select \n"
                + "sum(cd.monto_liquidacion_credito) as liquidacion_credito,\n"
                + "sum(cd.monto_recibo_pago) as recibo_pago,\n"
                + "sum(cd.monto_gasto) as gasto,\n"
                + "sum(cd.monto_vale)  as vale,\n"
                + "sum(cd.monto_recibo_pago) as ingreso,\n"
                + "sum(cd.monto_gasto+cd.monto_vale) as egreso,\n"
                + "(sum(cd.monto_recibo_pago)-sum(cd.monto_gasto+cd.monto_vale))  as diferencia \n"
                + "from caja_detalle cd\n"
                + "where cd.estado='EMITIDO' " + fecha;
        try {
            ResultSet rs = eveconn.getResulsetSQL(conn, sql, titulo);
            if (rs.next()) {
                double liquidacion_credito=rs.getDouble("liquidacion_credito");
                double recibo_pago=rs.getDouble("recibo_pago");
                double gasto=rs.getDouble("gasto");
                double vale=rs.getDouble("vale");
                double ingreso=rs.getDouble("ingreso");
                double egreso=rs.getDouble("egreso");
                double diferencia=rs.getDouble("diferencia");
                jFsuma_liquidacion_credito.setValue(liquidacion_credito);
                jFsuma_recibo.setValue(recibo_pago);
                jFsuma_gasto.setValue(gasto);
                jFsuma_vale.setValue(vale);
                jFsuma_ingreso.setValue(ingreso);
                jFsuma_egreso.setValue(egreso);
                jFsuma_diferencia.setValue(diferencia);
            }
        } catch (Exception e) {
            evemen.mensaje_error(e, sql, titulo);
        }
    }
    void boton_imprimir_caja_todos(){
        String fecha = evefec.getIntervalo_fecha_combobox(cmbfecha_caja, " cd.fecha_creado ");
        DAOcd.imprimir_caja_detalle_todos(conn, fecha);
    }
    public FrmRepMovimientoCaja() {
        initComponents();
        abrir_formulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltablatodos = new javax.swing.JTable();
        btnimprimir_caja_todos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbfecha_caja = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblcaja_suma = new javax.swing.JTable();
        jFsuma_recibo = new javax.swing.JFormattedTextField();
        jFsuma_vale = new javax.swing.JFormattedTextField();
        jFsuma_gasto = new javax.swing.JFormattedTextField();
        jFsuma_liquidacion_credito = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jFsuma_egreso = new javax.swing.JFormattedTextField();
        jFsuma_ingreso = new javax.swing.JFormattedTextField();
        jFsuma_diferencia = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("TABLA CAJA"));

        tbltablatodos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbltablatodos);

        btnimprimir_caja_todos.setText("IMPRIMIR CAJA TODOS");
        btnimprimir_caja_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimir_caja_todosActionPerformed(evt);
            }
        });

        jLabel1.setText("FECHA:");

        cmbfecha_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbfecha_cajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnimprimir_caja_todos)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbfecha_caja, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbfecha_caja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnimprimir_caja_todos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("DATO CAJA", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("SUMA CAJA"));

        tblcaja_suma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblcaja_suma);

        jFsuma_recibo.setBackground(new java.awt.Color(153, 255, 153));
        jFsuma_recibo.setBorder(javax.swing.BorderFactory.createTitledBorder("RECIBO-INGRESO"));
        jFsuma_recibo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFsuma_recibo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jFsuma_vale.setBackground(new java.awt.Color(255, 255, 102));
        jFsuma_vale.setBorder(javax.swing.BorderFactory.createTitledBorder("VALE-EGRESO"));
        jFsuma_vale.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFsuma_vale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jFsuma_gasto.setBackground(new java.awt.Color(255, 255, 102));
        jFsuma_gasto.setBorder(javax.swing.BorderFactory.createTitledBorder("GASTO-EGRESO"));
        jFsuma_gasto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFsuma_gasto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jFsuma_liquidacion_credito.setBackground(new java.awt.Color(204, 204, 204));
        jFsuma_liquidacion_credito.setBorder(javax.swing.BorderFactory.createTitledBorder("LIQUIDACION CREDITO"));
        jFsuma_liquidacion_credito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFsuma_liquidacion_credito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jFsuma_egreso.setBackground(new java.awt.Color(255, 255, 102));
        jFsuma_egreso.setBorder(javax.swing.BorderFactory.createTitledBorder("EGRESO"));
        jFsuma_egreso.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFsuma_egreso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jFsuma_ingreso.setBackground(new java.awt.Color(153, 255, 153));
        jFsuma_ingreso.setBorder(javax.swing.BorderFactory.createTitledBorder("INGRESO"));
        jFsuma_ingreso.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFsuma_ingreso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jFsuma_diferencia.setBackground(new java.awt.Color(102, 204, 255));
        jFsuma_diferencia.setBorder(javax.swing.BorderFactory.createTitledBorder("DIFERENCIA"));
        jFsuma_diferencia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFsuma_diferencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("RESUMEN:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jFsuma_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFsuma_egreso, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFsuma_diferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jFsuma_liquidacion_credito, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addComponent(jFsuma_recibo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFsuma_gasto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jFsuma_vale, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFsuma_liquidacion_credito)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFsuma_vale)
                        .addComponent(jFsuma_gasto)
                        .addComponent(jFsuma_recibo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFsuma_egreso)
                    .addComponent(jFsuma_ingreso)
                    .addComponent(jFsuma_diferencia)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("SUMA DE CAJA", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        DAOcd.ancho_tabla_caja_detalle_todos(tbltablatodos);
        DAOcd.ancho_tabla_caja_detalle_suma(tblcaja_suma);
    }//GEN-LAST:event_formInternalFrameOpened

    private void cmbfecha_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbfecha_cajaActionPerformed
        // TODO add your handling code here:
        actualizar_tabla_suma();
    }//GEN-LAST:event_cmbfecha_cajaActionPerformed

    private void btnimprimir_caja_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimir_caja_todosActionPerformed
        // TODO add your handling code here:
        boton_imprimir_caja_todos();
    }//GEN-LAST:event_btnimprimir_caja_todosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnimprimir_caja_todos;
    private javax.swing.JComboBox<String> cmbfecha_caja;
    private javax.swing.JFormattedTextField jFsuma_diferencia;
    private javax.swing.JFormattedTextField jFsuma_egreso;
    private javax.swing.JFormattedTextField jFsuma_gasto;
    private javax.swing.JFormattedTextField jFsuma_ingreso;
    private javax.swing.JFormattedTextField jFsuma_liquidacion_credito;
    private javax.swing.JFormattedTextField jFsuma_recibo;
    private javax.swing.JFormattedTextField jFsuma_vale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblcaja_suma;
    private javax.swing.JTable tbltablatodos;
    // End of variables declaration//GEN-END:variables
}
