/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIO.VISTA;

import BASEDATO.LOCAL.ConnPostgres;
import Evento.Color.cla_color_palete;
import Evento.JTextField.EvenJTextField;
import Evento.Jframe.EvenJFRAME;
import Evento.Jtable.EvenJtable;
import FORMULARIO.BO.*;
import FORMULARIO.DAO.*;
import FORMULARIO.ENTIDAD.*;
import java.sql.Connection;

/**
 *
 * @author Digno
 */
public class FrmTipo_tasa_cambio extends javax.swing.JInternalFrame {

    EvenJFRAME evetbl = new EvenJFRAME();
    EvenJtable eveJtab = new EvenJtable();
    private tipo_tasa_cambio entidad = new tipo_tasa_cambio();
    private BO_tipo_tasa_cambio BO = new BO_tipo_tasa_cambio();
    private DAO_tipo_tasa_cambio DAO = new DAO_tipo_tasa_cambio();
    private EvenJTextField evejtf = new EvenJTextField();
    Connection conn = ConnPostgres.getConnPosgres();
    cla_color_palete clacolor= new cla_color_palete();
    String creado_por="Digno";
    private void abrir_formulario() {
        this.setTitle("TASA CAMBIO");
        evetbl.centrar_formulario_internalframa(this);        
        reestableser();
        DAO.actualizar_tabla_tipo_tasa_cambio(conn, tbltabla);
        color_formulario();
    }
    private void color_formulario(){
        panel_tabla.setBackground(clacolor.getColor_tabla());
        panel_insertar.setBackground(clacolor.getColor_insertar_primario());
    }
    private boolean validar_guardar() {
        if (evejtf.getBoo_JTextField_vacio(txtdolar_gua_aduana, "DEBE CARGAR UN DOLAR ADUANA")) {
            return false;
        }
        if (evejtf.getBoo_JTextField_vacio(txtdolar_gua_mercado, "DEBE CARGAR UN DOLAR MERCADO")) {
            return false;
        }
        if (evejtf.getBoo_JTextField_vacio(txtreal_gua_aduana, "DEBE CARGAR UN REAL ADUANA")) {
            return false;
        }
        if (evejtf.getBoo_JTextField_vacio(txtreal_gua_mercado, "DEBE CARGAR UN REAL MERCADO")) {
            return false;
        }
        return true;
    }

    private void boton_guardar() {
        if (validar_guardar()) {
            entidad.setC3creado_por(creado_por);
            entidad.setC4dolar_gua_aduana(evejtf.getDouble_format_nro_entero(txtdolar_gua_aduana.getText()));
            entidad.setC5dolar_gua_mercado(evejtf.getDouble_format_nro_entero(txtdolar_gua_mercado.getText()));
            entidad.setC6real_gua_aduana(evejtf.getDouble_format_nro_entero(txtreal_gua_aduana.getText()));
            entidad.setC7real_gua_mercado(evejtf.getDouble_format_nro_entero(txtreal_gua_mercado.getText()));
            BO.insertar_tipo_tasa_cambio(entidad, tbltabla);
            reestableser();
        }
    }

    private void boton_editar() {
        if (validar_guardar()) {
            entidad.setC1idtipo_tasa_cambio(Integer.parseInt(txtid.getText()));
            entidad.setC3creado_por(creado_por);
            entidad.setC4dolar_gua_aduana(evejtf.getDouble_format_nro_entero(txtdolar_gua_aduana.getText()));
            entidad.setC5dolar_gua_mercado(evejtf.getDouble_format_nro_entero(txtdolar_gua_mercado.getText()));
            entidad.setC6real_gua_aduana(evejtf.getDouble_format_nro_entero(txtreal_gua_aduana.getText()));
            entidad.setC7real_gua_mercado(evejtf.getDouble_format_nro_entero(txtreal_gua_mercado.getText()));
            BO.update_tipo_tasa_cambio(entidad, tbltabla);
        }
    }

    private void seleccionar_tabla() {
        int idproducto = eveJtab.getInt_select_id(tbltabla);
        DAO.cargar_tipo_tasa_cambio(conn,entidad, idproducto);
        txtid.setText(String.valueOf(entidad.getC1idtipo_tasa_cambio()));
        txtdolar_gua_aduana.setText(evejtf.getString_format_nro_decimal(entidad.getC4dolar_gua_aduana()));
        txtdolar_gua_mercado.setText(evejtf.getString_format_nro_decimal(entidad.getC5dolar_gua_mercado()));
        txtreal_gua_aduana.setText(evejtf.getString_format_nro_decimal(entidad.getC6real_gua_aduana()));
        txtreal_gua_mercado.setText(evejtf.getString_format_nro_decimal(entidad.getC7real_gua_mercado()));
        btnguardar.setEnabled(false);
        btneditar.setEnabled(true);
    }
    private void reestableser(){
        txtid.setText(null);
        txtdolar_gua_aduana.setText(null);
        txtdolar_gua_mercado.setText(null);
        txtreal_gua_aduana.setText(null);
        txtreal_gua_mercado.setText(null);
        btnguardar.setEnabled(true);
        btneditar.setEnabled(false);
        btndeletar.setEnabled(false);
        txtdolar_gua_aduana.grabFocus();
    }
    private void boton_nuevo(){
        reestableser();
    }
    public FrmTipo_tasa_cambio() {
        initComponents();
        abrir_formulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_insertar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtdolar_gua_aduana = new javax.swing.JTextField();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btndeletar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtdolar_gua_mercado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtreal_gua_aduana = new javax.swing.JTextField();
        txtreal_gua_mercado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        panel_tabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltabla = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        panel_insertar.setBackground(new java.awt.Color(153, 204, 255));
        panel_insertar.setBorder(javax.swing.BorderFactory.createTitledBorder("CREAR DATO"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ID:");

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(204, 204, 204));
        txtid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("DOLAR-GUA-ADUANA:");

        txtdolar_gua_aduana.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtdolar_gua_aduana.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdolar_gua_aduanaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdolar_gua_aduanaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdolar_gua_aduanaKeyTyped(evt);
            }
        });

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ABM/nuevo.png"))); // NOI18N
        btnnuevo.setText("NUEVO");
        btnnuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ABM/guardar.png"))); // NOI18N
        btnguardar.setText("GUARDAR");
        btnguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ABM/modificar.png"))); // NOI18N
        btneditar.setText("EDITAR");
        btneditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btneditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btndeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ABM/eliminar.png"))); // NOI18N
        btndeletar.setText("DELETAR");
        btndeletar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndeletar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("DOLAR-GUA-MERCADO:");

        txtdolar_gua_mercado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtdolar_gua_mercado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdolar_gua_mercadoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdolar_gua_mercadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdolar_gua_mercadoKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("REAL-GUA-ADUANA:");

        txtreal_gua_aduana.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtreal_gua_aduana.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtreal_gua_aduanaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtreal_gua_aduanaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtreal_gua_aduanaKeyTyped(evt);
            }
        });

        txtreal_gua_mercado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtreal_gua_mercado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtreal_gua_mercadoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtreal_gua_mercadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtreal_gua_mercadoKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("REAL-GUA-MERCADO:");

        javax.swing.GroupLayout panel_insertarLayout = new javax.swing.GroupLayout(panel_insertar);
        panel_insertar.setLayout(panel_insertarLayout);
        panel_insertarLayout.setHorizontalGroup(
            panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_insertarLayout.createSequentialGroup()
                .addGroup(panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_insertarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdolar_gua_mercado, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(txtreal_gua_aduana)
                            .addComponent(txtreal_gua_mercado)
                            .addComponent(txtdolar_gua_aduana)))
                    .addGroup(panel_insertarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnnuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnguardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndeletar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_insertarLayout.setVerticalGroup(
            panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_insertarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtdolar_gua_aduana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdolar_gua_mercado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtreal_gua_aduana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtreal_gua_mercado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnnuevo)
                    .addComponent(btnguardar)
                    .addComponent(btneditar)
                    .addComponent(btndeletar)))
        );

        panel_tabla.setBackground(new java.awt.Color(51, 204, 255));
        panel_tabla.setBorder(javax.swing.BorderFactory.createTitledBorder("TABLA"));

        tbltabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbltabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbltablaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbltabla);

        javax.swing.GroupLayout panel_tablaLayout = new javax.swing.GroupLayout(panel_tabla);
        panel_tabla.setLayout(panel_tablaLayout);
        panel_tablaLayout.setHorizontalGroup(
            panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );
        panel_tablaLayout.setVerticalGroup(
            panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tablaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_tabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panel_tabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_insertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        boton_guardar();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        DAO.ancho_tabla_tipo_tasa_cambio(tbltabla);
    }//GEN-LAST:event_formInternalFrameOpened

    private void tbltablaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltablaMouseReleased
        // TODO add your handling code here:
        seleccionar_tabla();
    }//GEN-LAST:event_tbltablaMouseReleased

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
        boton_editar();
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        boton_nuevo();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void txtdolar_gua_aduanaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdolar_gua_aduanaKeyPressed
        // TODO add your handling code here:
        evejtf.saltar_campo_enter(evt, txtdolar_gua_aduana, txtdolar_gua_mercado);
    }//GEN-LAST:event_txtdolar_gua_aduanaKeyPressed

    private void txtdolar_gua_mercadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdolar_gua_mercadoKeyPressed
        // TODO add your handling code here:
        evejtf.saltar_campo_enter(evt, txtdolar_gua_mercado, txtreal_gua_aduana);
    }//GEN-LAST:event_txtdolar_gua_mercadoKeyPressed

    private void txtreal_gua_aduanaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtreal_gua_aduanaKeyPressed
        // TODO add your handling code here:
        evejtf.saltar_campo_enter(evt, txtreal_gua_aduana, txtreal_gua_mercado);
    }//GEN-LAST:event_txtreal_gua_aduanaKeyPressed

    private void txtreal_gua_mercadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtreal_gua_mercadoKeyPressed
        // TODO add your handling code here:
        evejtf.saltar_campo_enter(evt, txtreal_gua_mercado, txtdolar_gua_aduana);
    }//GEN-LAST:event_txtreal_gua_mercadoKeyPressed

    private void txtdolar_gua_aduanaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdolar_gua_aduanaKeyReleased
        // TODO add your handling code here:
        evejtf.getString_format_nro_entero(txtdolar_gua_aduana);
    }//GEN-LAST:event_txtdolar_gua_aduanaKeyReleased

    private void txtdolar_gua_mercadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdolar_gua_mercadoKeyReleased
        // TODO add your handling code here:
        evejtf.getString_format_nro_entero(txtdolar_gua_mercado);
    }//GEN-LAST:event_txtdolar_gua_mercadoKeyReleased

    private void txtreal_gua_aduanaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtreal_gua_aduanaKeyReleased
        // TODO add your handling code here:
        evejtf.getString_format_nro_entero(txtreal_gua_aduana);
    }//GEN-LAST:event_txtreal_gua_aduanaKeyReleased

    private void txtreal_gua_mercadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtreal_gua_mercadoKeyReleased
        // TODO add your handling code here:
        evejtf.getString_format_nro_entero(txtreal_gua_mercado);
    }//GEN-LAST:event_txtreal_gua_mercadoKeyReleased

    private void txtdolar_gua_aduanaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdolar_gua_aduanaKeyTyped
        // TODO add your handling code here:
        evejtf.soloNumero(evt);
    }//GEN-LAST:event_txtdolar_gua_aduanaKeyTyped

    private void txtdolar_gua_mercadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdolar_gua_mercadoKeyTyped
        // TODO add your handling code here:
        evejtf.soloNumero(evt);
    }//GEN-LAST:event_txtdolar_gua_mercadoKeyTyped

    private void txtreal_gua_aduanaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtreal_gua_aduanaKeyTyped
        // TODO add your handling code here:
        evejtf.soloNumero(evt);
    }//GEN-LAST:event_txtreal_gua_aduanaKeyTyped

    private void txtreal_gua_mercadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtreal_gua_mercadoKeyTyped
        // TODO add your handling code here:
        evejtf.soloNumero(evt);
    }//GEN-LAST:event_txtreal_gua_mercadoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndeletar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_insertar;
    private javax.swing.JPanel panel_tabla;
    private javax.swing.JTable tbltabla;
    private javax.swing.JTextField txtdolar_gua_aduana;
    private javax.swing.JTextField txtdolar_gua_mercado;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtreal_gua_aduana;
    private javax.swing.JTextField txtreal_gua_mercado;
    // End of variables declaration//GEN-END:variables
}
